services:
- type: web
  name: lcm-frontend
  env: node
  buildCommand: cd frontend && npm install && npm run build
  startCommand: cd frontend && npm run preview
  plan: free

- type: web
  name: lcm-backend
  env: python
  plan: free
  repoPath: backend
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app.app:app
