services:
- type: web
  name: lcm-frontend
  env: node
  rootDir: frontend
  buildCommand: npm install && npm run build
  startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
  plan: free

- type: web
  name: lcm-backend
  env: python
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app.app:app
  plan: free
